### ISSUE TITLE
[Proposal] Rebranding Rust Gamedev Meetup channels

### ISSUE THREAD

**Issue by AngelOnFira** [rust-gamedev/wg#104]
I'm wondering if it might be worth rebranding the existing channels that are titled "gamedev meetup" (Youtube, Twitch) to just be "Rust Game Development". They have a small/medium-size following, but it would be nice to add other content than just the meetup to them. Specifically, some ideas that I have:

- Youtube videos that showcase many games
- Streams for meetings, hosting other game dev channels on Twitch

Current links:
Twitch: https://www.twitch.tv/rustgamedevmeetup
Youtube: https://www.youtube.com/channel/UCrbatFmtTIvX3BCgsXOy96w

Note; I don't know if I can actually change the Twitch username, but a switch to a new channel for the meetups shouldn't be too bad.

Any thoughts welcome!

**Comment by 17cupsofcoffee** [comment]
Sounds sensible to me.

You [can change your Twitch channel name](https://blog.twitch.tv/en/2017/02/24/the-hype-is-real-name-changes-are-here-c629c4697154/), apparently. I think this would be preferable to creating a new channel, to avoid losing any follows the existing one's built up 🙂

**Comment by AngelOnFira** [comment]
I'll be closing this, as it's resolved. The new links are:

Twitch: https://www.twitch.tv/rustgamedev
Youtube: https://www.youtube.com/c/RustGameDevelopment
