### ISSUE TITLE
Status of the project "ECS Bench Suite"

### ISSUE THREAD

**Issue by 64kramsystem** [rust-gamedev/wg#130]
Somebody [asked on Discord](https://discord.com/channels/442252698964721669/587379891758956544/1043021368897323008) the status of the project [ECS Bench Suite](https://github.com/rust-gamedev/ecs_bench_suite).

I've had a look and it seemed abandoned-ish. Is there any intention to maintain it? @ozkriff mentioned [Ralith](https://github.com/Ralith) and @erlend-sh.

Generally speaking, archiving a repository makes the status unambigious. In this particular case, this is even a more sensitive topic, since presenting outdated results can be misleading.

In theory, maintaining it should be very lightweight, as API changes should be small (I haven't checked though), and the diagrams are automatically updated (after the test suite is run).

On the other hand, "serious" maintenance is on another level, as it requires discussing and critically reviewing the benchmark themselves (in practice, dealing with issues like [this](https://github.com/rust-gamedev/ecs_bench_suite/issues/25)).

I'm no fan of microbenchmarks, so I'd archive it.

**Comment by 64kramsystem** [comment]
Reasons why I'm posting it here:

1. that repository seems unmaintained, so this issue may not gather attention
2. the issue [Tracking: Important Issues Filed Elsewhere](https://github.com/rust-gamedev/wg/issues/61) seems unmaintained as well

**Comment by erlend-sh** [comment]
It seems to have served its purpose.

> [ECS Bench Suite] arguably went quite well even though it’s not that actively updated; I like to think we collectively realized that speed is only one aspect of an ECS, and a rather small one at that once a baseline of performance has been established.

I’m in agreement with archiving it.

**Comment by alice-i-cecile** [comment]
From the Bevy perspective: I'm on board with archiving this. Definitely interested in sharing knowledge (including places where projects are leaving performance on the floor) between ECS projects going forward, but I don't think that the payoff on maintaining microbenchmarks is there.

**Comment by Ralith** [comment]
It'd have some value if it was actively maintained, but nobody's stepping up to do so, so let's drop it rather than leaving it in limbo indefinitely.

**Comment by 64kramsystem** [comment]
Thanks for the input :smile: 

I'm going to wait until Sat Nov 26, then, if there aren't any dissenting opinions, I'm going to add a `Status` section to the header, with the text Erlend provided, and archive the repository.
