### ISSUE TITLE
Meeting schedule

### ISSUE THREAD

**Issue by AlexEne** [rust-gamedev/wg#16]
Should we make `Wednesday 8PM BST` the standard time to hold meetings and put this in the README?

Being mindful of everyone's (free) time, I would propose we have these meetings [every two weeks](https://www.google.com/search?client=firefox-b-d&q=bi+weekly). But once a week is also an option. 

They are for the purpose of:
1. Sync and discussion on various things happening
2. Triage

Decisions will always happen on github issues.

**Comment by erlend-sh** [comment]
Time is fine for me (CEST here).

> Sync and discussion on various things happening

I'd like us to spend most our time on the sync part, as complementary to triaging. Since decisions will be made on GitHub issues, it follows that most of our discussion should happen there as well.

**Comment by AlexEne** [comment]
Unless anyone else has anything against this I am going to open a PR with a meeting schedule.

**Comment by 17cupsofcoffee** [comment]
How are the meetings ran (or is that still an open question)? It seems to vary from WG to WG whether they're text-based or over some kind of audio/video call.

**Comment by Lokathor** [comment]
Also, a quick search says that `BST` is basically `GMT +0` ?

**Comment by 17cupsofcoffee** [comment]
@Lokathor BST is one hour ahead of GMT/UTC - it's daylight savings in the UK at the minute.

**Comment by Osspial** [comment]
Every other Wednesday at that time should work for me. Is there a set amount of time these would go on for, or would they just last for as long as there's stuff to talk about?

**Comment by kvark** [comment]
@Osspial 
We shouldn't extend it for more than an hour. That's the practice people use that allow them to pack more meetings in a day.

**Comment by AlexEne** [comment]
We will have audio/video calls over zoom. For text chats discord is another option https://discord.gg/j6QJsMd

**Comment by Lokathor** [comment]
Hangouts works well enough and doesn't require an install of any sort. The main difference from Discord is that video would be possible with screenshare or whatever.

**Comment by AlexEne** [comment]
+1 for Hangouts from me too. I will update https://github.com/rust-gamedev/wg/pull/19 with a hangouts or whatever else link if needed.

**Comment by kvark** [comment]
I can schedule zoom meetings beyond 40 mins, fwiw

**Comment by AlexEne** [comment]
I merged my PR with the initial schedule / hangouts link.
Sorry if it looks rushed, but I kind of rushed it because Wednesday is soon and I wanted us to have something as soon as possible :D.

We can discuss alternative meeting locations than hangouts in later Issues.
