### ISSUE TITLE
RLS for huge projects

### ISSUE THREAD

**Issue by AlexEne** [rust-gamedev/wg#22]
## The problem(s)

1. RLS is not ideal for big projects with hundreds of dependencies and XX lines of code (I have no idea what the limit of breaking RLS is here). Unfortunately there are not many projects of Unreal/Unity/insert-your-favorite-engine-here out in the open that we can use as a test repo.

2. There is a second level of complication due to the fact that there is no clear owner where these bugs should go: as RLS makes use of other things like the compiler itself or racer. So what crashed is unclear (is it RLS, is it Racer, etc.). 

I will focus on problem 1 in this issue.

## The solution
The main idea is that we reproduce these issues that these big projects are facing in a reliable way, then have a test-case that the RLS or other developers can use to stress test.

In the future, a CI test for RLS or other analyzer projects could look like:
1. Unzip file with code for rustc or another_big_project.
2. Spawn RLS to analyze it.
3. Open to file x.rs
4. Modify a letter in this method and replace it with `bla`
5. Check that you didn't crash.

So I have a few proposals for these projects:
- Use rustc?
- Servo / webrenderer?
- Write a hello world test app that includes a ton of dependencies (?)

## Next steps
1. Create a reliable stress scenario that breaks RLS or it's dependencies.
2. Open an issue on RLS and  see if there's enough data in our scenario for the devs to do reproduce and do a fix.
3. Provide a repository that all projects that consider writing an analyzer can use as part of their CI. Such a project includes the problematic rust code as well as python scripts that you start as part of your test and they modify files, delete them etc, trying to make your analyzer crash.

## Extra material
I also a study on what the current open bugs on RLS/Racer mention about stability and none of the projects have any kind of stress-tests that I could find. There is a [fuzzing suggestion](https://github.com/rust-lang/rls/issues/673) for RLS but that's about it.

All RLS bugs mentioning crashes:
https://github.com/rust-lang/rls/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+crash

Racer panics:
https://github.com/racer-rust/racer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+panic

**Comment by Lokathor** [comment]
A known good rustc or servo may be appropriate in scale, but my experience with PRing rustc itself is that the build process is _just weird enough_ that RLS will say there's errors even when actual CI passes.

So to start we need something large but preferably without even a `build.rs`, just a totally plain `cargo build` cycle.

Gotta crawl before you walk.

**Comment by AlexEne** [comment]
As long as it's easy to reproduce the issue in RLS, this should matter less if it has or hasn't got a build.rs or if build is strange. Even if the build fails, I want RLS to keep working and not crash. That's most likely a valid scenario 99% of the time anyway as you edit the code the build will mostly fail.

**Comment by msiglreith** [comment]
Probably worth syncing up with the wg for the successor of RLS: https://github.com/rust-lang/compiler-team/tree/master/working-groups/rls-2.0

**Comment by AlexEne** [comment]
The link doesn't work

**Comment by msiglreith** [comment]
New link: https://github.com/rust-lang/compiler-team/tree/wg-traits-sprints/working-groups/rls-2.0
Apparently the compiler working group (where RLS is a part of it) is currently setting up a website :>

**Comment by AlexEne** [comment]
I will sync with them because I want what we build here to be reusable between RLS versions. 

Maybe it just means using vscode and installing their latest master version, then starting to mess around with files in the editor while at the same time checking for RLS to not crash.

**Comment by AlexEne** [comment]
I have tried rust-analyzer and did some study in this space. I've basically switched to it and also started donating as it's clearly the future :). I believe Embark are also convinced by this so I don't think that this project that I wanted to start is of any use now.

https://opencollective.com/rust-analyzer/
