### ISSUE TITLE
Would we eventually want a Discourse forum?

### ISSUE THREAD

**Issue by erlend-sh** [rust-gamedev/wg#3]
For the time being I think this repo can cover our async discussion needs, but further down the line I would strongly recommend setting up a dedicated Discourse forum, which we can have for free:

https://free.discourse.group/
https://blog.discourse.org/2018/04/effectively-using-discourse-together-with-group-chat/

(Disclaimer: I was an employee at Discourse until very recently.)

**Comment by AlexEne** [comment]
I was hoping @skade could do the gamedev rust room. I didn't think very much about that but it's a good callout.

**Comment by skade** [comment]
Hi, I'll open the discord room over the weekend, sorry that got delayed.

Discourse, I have a (personal) opinion: I would prefer if the Rust had less forums, but with better grouping. I line the [mozilla discourse](https://discourse.mozilla.org).

**Comment by erlend-sh** [comment]
Should the need arise, could we possibly have a category set up for the WG on one of the Rust forums?

**Comment by Lokathor** [comment]
Since we ended up getting that Discord channel I'm going to close this.

Also, I think that the `zulip` would be better as a "non-github, non-realtime" location, since there's already a lot of wgs there.

Feel free to re-open this later if this need arises.
