### ISSUE TITLE
Logo :)

### ISSUE THREAD

**Issue by AlexEne** [rust-gamedev/wg#4]
We need a logo for this, so if anyone has some ideas just reply to this.

**Comment by Vengarioth** [comment]
A pixelated packman style ferris? :)

**Comment by AlexEne** [comment]
That would be awesome :D

**Comment by erlend-sh** [comment]
How would you make it Pac-Man style? Rounder and open mouth, but still with claws?

Maybe we could use one of these while we wait for bespoke art:

https://users.rust-lang.org/t/ferris-as-an-8-bit-sprite/25346
https://www.reddit.com/r/rust/comments/62yv2i/i_made_a_rustacean_pixelart_for_rplace/

**Comment by AlexEne** [comment]
That pixelated Ferris looks great, if the author is ok with it I can use it.

**Comment by Vengarioth** [comment]
My idea was something along the lines of this, :) let me know if you want it and there is still need, then i'll explore this some more.
![image](https://user-images.githubusercontent.com/1100638/59358269-891d7f80-8d2c-11e9-963c-7db649bbda2f.png)

**Comment by ozkriff** [comment]
![image](https://user-images.githubusercontent.com/662976/59359042-52e4fd80-8d36-11e9-8f7e-3ac90ab6bfbe.png)

**Comment by AlexEne** [comment]
@ozkriff that looks good. I will assume you made it and are ok with us using it. Thank you :D

**Comment by ozkriff** [comment]
> I will assume you made it and are ok with us using it

@shmutalov has drawn it but he has given the permission to use it in the rust gamedev context.

**Comment by shmutalov** [comment]
@ozkriff @AlexEne it's open source and free to use :+1: I am ok with that

**Comment by AlexEne** [comment]
I will add them in a /assets folder thanks
