### ISSUE TITLE
Rust Gamedev WG Website Design

### ISSUE THREAD

**Issue by zicklag** [rust-gamedev/wg#43]
Hey everybody, I'm opening this issue for discussing what we want to get out of the Rust Gamedev WG website and what technology we might be able to use to build the site.

I had seen some talk about the website on #42 including:

> @Lokathor: 
> I think the biggest problem with hoping for too much from the website is that none of us have super web skills, so we're all kinda just fumbling with the website as "something we could maybe turn into a newsletter blog thing".

I have some web design experience and I am currently training a colleague of mine to design sites using [Quasar](https://quasar.dev). If we can get together what we want the site to consist of, me and my colleague might be able to spend some time designing it.

As an example of what Quasar can accomplish you can check out my company's website, [Katharostech.com](https://katharostech.com).

Katharostech.com is backed by a [Ghost](https://ghost.org/) blog to create the content, but it would be simple to pull content for the site from anywhere. If we wanted to, it would likely be trivial to have the site backed by Markdown files in a GitHub repo.

There are some big advantages to designing a site with Quasar:

* Data can be pulled from anything that has an API. If we wanted to display a filtered list of GitHub issues on one page and a list of Ghost posts on another, or even grab crate info off of crates.io, all of that would be possible.
* Quasar comes with a massive library of components. Using Quasar's components allows you to shortcut a lot of the work required to make a beautiful and responsive website.
* Quasar is extremely flexible. We can start small and simple and no matter how large or complicated we want the site to get in the future, Quasar will still be suitable.

There is also a couple of disadvantages to other options:

* Quasar is more complicated by way of the fact that you have to build your design from the ground up, as opposed to having an out-of-the-box solution like you would get with a static site generator such as Hugo or mdbook.
* Search engine optimization requires the use of a prerenderer such as [Rendora](https://github.com/rendora/rendora) because Quasar apps are SPA's. At Katharos Technology we use Rendora and get great results out of it, but you have to host it on your own server, so GitHub pages wouldn't be enough to host the site with proper SEO.

I'd love to hear your thoughts!

**Comment by ZeGentzy** [comment]
What's the goal of the website? If it's like a blog thing, you can easily put something together with wordpress in under a day. I got like 0 web experience and still managed to do so with gentz.rocks. Hell, raw html isn't all too bad tbh if it's only going to be a couple pages.

**Comment by zicklag** [comment]
That's true. It all depends on what we are going for. I don't know exactly what the goal of the website is going to be, which is a big part of what I wanted to discuss.

If we are only going for a simple blog then it would likely be best to use a tool like [Hugo](https://github.com/gohugoio/hugo) to generate an HTML site from Markdown that can be hosted for free on GitHub pages.

On the other hand, If we want to make the site a more general tool that hosts a blog and aggregates data from around Rust gamedev community, then Quasar would be better suited and more customizable.

We first need to figure out what we want to accomplish, then we can decide what tool best accomplishes the goal. I brought up Quasar because I have experience with it and because knowing what tools we have available may change what we attempt to accomplish with the website.

**Comment by aclysma** [comment]
I haven't seen any suggested function for the website that calls for anything more than a static site generator. I would lean towards keeping it as simple as reasonably makes sense. It seems like the wasm and embedded rust working groups haven't needed anything beyond that.

One possibility might be if we wanted to move away from github to something else. (i.e. discourse) Maybe at that point it would make sense to have a non-static site.

**Comment by ozkriff** [comment]
This issue looks like a duplicate of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/4 to me.

Also, a basic version of https://rust-gamedev.github.io is already and is based on Jekyll.

**Comment by zicklag** [comment]
Ah, I hadn't seen the other issue yet. I'll close this one, then.
