### ISSUE TITLE
Meeting Agenda: September 4th, 2019

### ISSUE THREAD

**Issue by Lokathor** [rust-gamedev/wg#52]
It's been 2 weeks time for another meeting.

Same time as usual, same place as usual.

I know it's late notice, but put agenda items here.

---

EDIT: Proposed Topics:

* @kvark: GL in `raw-window-handle`
* @msiglreith: Memory management, including "[placement new](https://github.com/rust-gamedev/wg/issues/48)"
* @msiglreith: Audio, (https://github.com/rust-gamedev/wg/issues/40)
* @Wodann: Adopting rust in industry
* @aclysma: How we should cope with the [Known Issues List](https://github.com/rust-gamedev/wg/pull/44)

**Comment by kvark** [comment]
Would be good to discuss GL support in raw-window-handle if we run out of topics - https://github.com/rust-windowing/raw-window-handle/issues/5

**Comment by JeanMertz** [comment]
> Same time as usual, same place as usual.

For those who haven't attended before, it's a good idea to keep repeating these details, even if they are known to you and the core members.

Having said that, I won't be attending, but I figured it'd be good to keep the barriers to participation as low as possible for everyone.

**Comment by Lokathor** [comment]
Good point!

Meeting is on google hangouts, details in the readme file: https://github.com/rust-gamedev/wg/blob/master/README.md#join-the-fun, including a link that will convert the meeting time to your local time zone.

**Comment by msiglreith** [comment]
Memory Management (including https://github.com/rust-gamedev/wg/issues/48) or Audio (https://github.com/rust-gamedev/wg/issues/40) could be interesting topics

**Comment by Wodann** [comment]
I feel like it'd be good to discuss how we can involve Rust adopters in the industry in the working group (e.g. Embark Studios & Ready at Dawn).

**Comment by aclysma** [comment]
I'd like to discuss the known issues list (https://github.com/rust-gamedev/wg/pull/44) and what the next steps might be for engaging with the language team on some of these. (Example: opening bugs in rust-lang, getting the bugs triaged, requesting mentoring instructions, etc.)

**Comment by Lokathor** [comment]
@kvark: Alex is still on vacation, so if you could lead again this week that'd be very helpful. I've collected the suggestions into the top post of the issue for easy reference.

**Comment by kvark** [comment]
ok, sure

**Comment by Osspial** [comment]
Hey, all,

Sorry I missed the last meeting without saying anything - I was out of town at that point, and I didn't have the time to drop in. Anyway, I just got back from like a month of travel, and I need to decompress somewhat, so I don't think I'll be in this week's meeting either. Message me on Discord if there's anything pressing you need to ask me about.

**Comment by kvark** [comment]
Meeting notes:

## Placement new

@aclysma: constructing a value involves a copy
(A) Either introduce a solution, or have a page describing:
  - what workarounds exist
  - what are the good/bad cases from the compiler point of view
  - status of bugs

@Lokathor: Can do today with `&mut MaybeUninit`.
Has to guarantee all fields are written.
Alignment? if mutable reference is passed, it has to be aligned.

RFC for copyless into rust code? already happened to some extent.

@msiglreith has a case in ECS, need placement new, (A) will try `MaybeUninit`.

## Audio

`RustAudio` is a group.
`cpal` has issues, reworking the event loop.
Does `rodio` need to be split (DSP graph and stuff)?

@msiglreith: need something lower level.
Vulkan for audio. Manyally allocate and fill buffers.
Call-back based.
C++ is trying to standardize an audio library as well (std-audio, similar to `cpal`).
We could re-use existing C++ bits and gradually oxidize, or just learn from it.
TODO: Ask Embark for what they need/do.

@Lokathor: SDL does that low-level stuff.

@msiglreith: close the gap between production-ready libraries and the ecosystem.
Need better bindings for FMOD, wwise.

(A) investigate SDL, see if there is a place for lower-level explicit audio library

## Rust in the industry

Embark, Ready at Dawn, etc
Mostly missing from our discussions...

@Wodan: (A) reach to Ready at Down
Other: (A) reach to Embark

@Lokathor: ask them to report issues of building packages on consoles

@aclysma: ask on GDC. Suggestion is filed for the roundtable (yay!).

## Known Issues List

@kvark Duplicating issues is not the best. Having just a list is sufficient.

Embark format: https://github.com/EmbarkStudios/rust-ecosystem/issues/36

@Lokathor: should accept the RR and address the problems.

(A) go through the open action items at the beginning of a call!

---

Thanks everyone for participating! I'll move the "(A)" (action items) into a list somewhere.

**Comment by Lokathor** [comment]
The meeting is done so I'm closing this.

The next meeting issue is now open, https://github.com/rust-gamedev/wg/issues/53

**Comment by ZeGentzy** [comment]
Was this meeting recorded?

**Comment by Lokathor** [comment]
Not as far as I'm aware. I've been doing the meetings from a spare room at work so I can no longer record them myself.

**Comment by ethindp** [comment]
Its sept. five now, but can we add Accessibility for persons with
disabilities to the next meetings agenda? I haven't attended any of
these before (and honestly haven't been very active) but am very
interested in developing games in Rust as a blind individual myself.
Discussing accessibility -- or providing crates for this (one already
exists for text-to-speech) -- would be awesome. I'd ask it to be some
kind of mandate, but that's going a bit far. I would be happy to
discuss accessibility of games in another issue, since this one has
probably quite nicely yanked this one off-topic. :)

On 9/4/19, Lokathor <notifications@github.com> wrote:
> Not as far as I'm aware. I've been doing the meetings from a spare room at
> work so I can no longer record them myself.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/rust-gamedev/wg/issues/52#issuecomment-528192393


-- 
Signed,
Ethin D. Probst

**Comment by Lokathor** [comment]
@ethindp how about opening a fresh issue to discuss the subject? It certainly sounds important to try and provide games for the whole game-liking population of the world.
