### ISSUE TITLE
Meeting Agenda: September 18th, 2019

### ISSUE THREAD

**Issue by Lokathor** [rust-gamedev/wg#53]
(Regular reminder, meetings are public on Google Hangouts, info is in [the repo's readme](https://github.com/rust-gamedev/wg/blob/master/README.md#join-the-fun))

### Action Items From [Last Meeting](https://github.com/rust-gamedev/wg/issues/52)

* [x] Did we put last meeting's action items in this meeting's agenda?
* [ ] Gather info/guidance around "placement new" language feature or possible workarounds.
* [ ] Try working with something like `MyType::new_here(&mut MaybeUninit<MyType>)`.
* [ ] Investigate lower level sound API
* [ ] Contact Ready At Dawn for more info about their Rist usage, possible closer collaboration.
* [ ] Contact Embark Studios for more info about their Rist usage, possible closer collaboration.

### Agenda This Week

* TBD, post here if you want something to get discussed.

**Comment by kvark** [comment]
Chat! There is a bit of news from Mozilla - http://exple.tive.org/blarg/2019/09/06/forward-motion/

**Comment by Wodann** [comment]
Had a chat with RaD's CTO (Andrea Pessino) and Dan Olson, a principal engineer at Treyarch, about Rust adoption in AAA studios. Andrea Pessino expressed interest in joining our biweekly meeting to explain some of the ecosystem problems they are facing.

The main Twitter conversation thread: https://twitter.com/AndreaPessino/status/1169677656528310272

**Comment by Lokathor** [comment]
Weekend check-up: If you had any agenda items you were meaning to get on the list now is a good time, the meeting is this upcoming Wednesday.

**Comment by kvark** [comment]
Sorry, I just realized I'm not able to attend on Wednesday at this time, at all. Would appreciate if we consider moving this an hour earlier, or to a different day.

**Comment by Wodann** [comment]
I'm okay with moving it to 18:00 UTC.

**Comment by Lokathor** [comment]
also usually works for me, let's check with others at the meeting

**Comment by mtak-** [comment]
Is this still happening? The some folks at Brainium Studios (where I work) were planning on attending. Totally ok with the time change.

**Comment by Lokathor** [comment]
In about 30 minutes. I'll be around. If not enough people show up that's okay

**Comment by AlexEne** [comment]
I'll be there

**Comment by distransient** [comment]
Nice meeting everyone :+1:

**Comment by Lokathor** [comment]
Meeting went great! @AlexEne took notes which will be posted soon enough, and the issue for the next meeting is now available: https://github.com/rust-gamedev/wg/issues/55

**Comment by Lokathor** [comment]
> Gamedev WG Meeting: 2019-Sept-18
> Your video was uploaded. Once processing is complete, your video can be found at https://youtu.be/8O8Iu1kpsOk

**Comment by Wodann** [comment]
@AlexEne Could you still post the minutes from the previous meeting?

**Comment by AlexEne** [comment]
# Meeting notes 18-09-2019

- Placement new? -- Propose on the internals forum.
- Complaints about sound, nobody knows anything. (?)
- Alto  directly (OpenAL + layer on top).
- Cpal too much latency
- Andrea Pessino would be able to join the meeting at some point.
- Mobile games in rust:
  - Testing with Jenkins + IOS/Android & Not running tests on mobile.
  - Cannot do `cargo run` and target  Android/IOS. 
  - Have to create xcode project and configure it.
  - Android is the most challenging.
  - Dependencies don't really work.
  - Rust on mobile repo.
  - Winit basically just works
  - Cargo is a weak point as it has a workspace project structure and setting features on a project requires --manifest-path, before giving any features + Not enough support for custom builds.
   - More fine-grained control over link arguments.
    - 4 Minutes full build, incremental builds 3-4 seconds.
    - Compile times and killing failures and proc-macro crates.
    - Link time is the worst for daily life tests. (10-12s link times)
        - cprefferdynamic links to the standard library in a dynamic way.
    - Turned incremental compilation off reduced link times (?)
    - Debug - 40MB
    - Stripped - 6MB
    - Hot-reloading and DLLs.
    - Cargo not set up to do DLLs that get linked at runtime
    - cargo doesn't want post build args.
    - cargo make (?) for next week wihtout cargo doing anything
    - gfx-rs and metal backend/vulkan backend.

- https://github.com/rust-lang/wg-allocators
- Placement new: check how do rust-embedded do it?
- Survey status?.

**Comment by AlexEne** [comment]
Meeting notes 18-09-2019

    Placement new? -- Propose on the internals forum.

    Sound
        Alto directly (OpenAL + layer on top).
        Cpal too much latency

    Andrea Pessino would be able to join the meeting at some point.

    Mobile games in rust:
        Testing with Jenkins + IOS/Android & Not running tests on mobile.
        Cannot do cargo run and target Android/IOS.
        Have to create xcode project and configure it.
        Android is the most challenging.
        Dependencies don't really work.
        Rust on mobile repo.
        Winit basically just works
        Cargo is a weak point as it has a workspace project structure and setting features on a project requires --manifest-path, before giving any features + Not enough support for custom builds.
        More fine-grained control over link arguments.
        4 Minutes full build, incremental builds 3-4 seconds.
        Compile times and killing failures and proc-macro crates.
        Link time is the worst for daily life tests. (10-12s link times)
            cprefferdynamic links to the standard library in a dynamic way.
        Turned incremental compilation off reduced link times (?)
        Debug - 40MB
        Stripped - 6MB
        Hot-reloading and DLLs.
        Cargo not set up to do DLLs that get linked at runtime
        cargo doesn't want post build args.
        cargo make (?) for next week wihtout cargo doing anything
        gfx-rs and metal backend/vulkan backend.

    https://github.com/rust-lang/wg-allocators

    Placement new: check how do rust-embedded do it?

    Survey status?.
