### ISSUE TITLE
add to the rust team repository

### ISSUE THREAD

**Issue by nikomatsakis** [rust-gamedev/wg#54]
Hey! So I'd like to see this working group listed on the Rust website! Do you think you all could make a PR to https://github.com/rust-lang/team, similar to https://github.com/rust-lang/team/pull/103, to list yourselves, a link to this github org, etc?

(Please cc me or the core team on the pull request, too, to help make sure I see it; I suck at GH notifications.)

Thanks! ❤️

**Comment by nikomatsakis** [comment]
Oh, also, @erlend-sh / @AlexEne, maybe one of you would be able to attend the [Project Leadership Sync meeting](https://internals.rust-lang.org/t/project-leadership-sync-meeting/10552)? (Ping me on discord and I'll add you to the calendar invite.)

**Comment by nikomatsakis** [comment]
(I'm presuming you're the leads)

**Comment by AlexEne** [comment]
Hey, there is an open PR, I'll clean it up and ping you on it.

**Comment by AlexEne** [comment]
I actually opened [this](https://github.com/rust-lang/team/pull/124). I can try to join once in a while, but it's kind of intense at the hour it is for me.  Maybe join from time to time and split with  @kvark / @erlend-sh?

**Comment by kvark** [comment]
Looks like it's a bi-weekly meeting, so splitting between us three means less than an hour per month. I can do it.

**Comment by AlexEne** [comment]
Cool, let's try to set up a schedule, I am going to follow-up on this in a different email.
I am ultra busy with various (unrelated to rust) things in this period and that's why I really appreciate the help here :)
