### ISSUE TITLE
We need more people with git repo permissions

### ISSUE THREAD

**Issue by Lokathor** [rust-gamedev/wg#58]
Currently there are not many people who have permissions to the git repo. This leads to problems with issue triage, PR management, wiki updates, and so on.

It has been proposed that we widen the pool of who has permissions to the repo so that we can respond to events more promptly.

Uh, discuss, I guess.

**Comment by 17cupsofcoffee** [comment]
I've got access to the website repo, so I've been trying to help a bit with triage there - would be open to helping out here as well if needs be.

**Comment by AlexEne** [comment]
@Lokathor I've added you to the github org, tell me if you can at least triage issues. Maybe creating teams is a good idea as we expand as it simplifies managing these things

**Comment by AlexEne** [comment]
Alright, so I did a bit of cleanup in our org, branches require PRs with 1 approval in order to be merged. Please check that approve button.   
Everyone in the org can now merge things.   
I didn't add teams yet but for now this should improve things a bit

**Comment by Lokathor** [comment]
I'm going to close this as "fine for now". We seem to be doing well with issues and with the newsletter.

We can open another issue if this becomes a problem again.
