### ISSUE TITLE
Transfer ownership of arewegameyet to gamedev wg

### ISSUE THREAD

**Issue by termhn** [rust-gamedev/wg#64]
I've created an [issue](https://github.com/doppioslash/arewegameyet/issues/210) on the arewegameyet repository to see if the owner would be interested in transferring ownership to this wg. The motivations for this are listed in that issue, and I'm posting this here as a tracker and to see if it's something the wg would be interested in.

**Comment by Lokathor** [comment]
I think they are not interested, and even then if they were, our charter males it hard to have a good ecosystem guide because we aren't supposed to have opinions, and opinions are at the heart of a good guide.

**Comment by termhn** [comment]
If so then that's fine, their prerogative for sure.

As far as the second concern, as far as I see it, it's not meant to be a guide but just a list of resources and overview of the ecosystem.

**Comment by Wodann** [comment]
@Lokathor the repo has been [transferred](github.com/rust-gamedev/arewegameyet) . Can you close this issue?

**Comment by ozkriff** [comment]
> [There's this repo, the hosting (atm it's on S3), _and 3 domains: .com, .org, .rs_.](https://github.com/rust-gamedev/arewegameyet/issues/110#issuecomment-545583782)

I think the WG should get the domains and decide who from the WG pays for them now before closing this? (It was discussed briefly on discord)

**Comment by Lokathor** [comment]
Closing, since the transfer happened.

**Comment by Wodann** [comment]
@erlend-sh @AlexEne is there a budget for the wg, or will this just have to be out of pocket expenses?

**Comment by Lokathor** [comment]
@wodann if there's more to discuss I'll open it back up.

**Comment by JeanMertz** [comment]
> I think the WG should get the domains and decide who from the WG pays for them now before closing this? (It was discussed briefly on discord)

I've [mentioned it before](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/24#issuecomment-538290547) but I'll briefly mention it again in this context:

I'm passively following this WG and am cheering for all of you. I don't participate in active discussions, but if someone sets up a shared Patreon or some other ways to donate some money to the WG for these kinds of expenses, I'd be happy to chip in.

**Comment by AlexEne** [comment]
There's no budget for these.
We need to set up some sort of bucket for this kind of expenses. there's this, mailchimp, etc.
So, if anyone knows an easy way to create a pot just mention it here. Maybe patreon would be a good idea, maybe just a paypal jar I think they're called. 
Anyway, I will look into alternatives in the following week and come up with a proposal.

**Comment by icefoxen** [comment]
As of now, Amazon's domain prices (in USD) are: $12/yr for .com, free transfer.  $12/yr for .org, free transfer.  I don't see any options for .rs distressingly, but looking at some other registrars they seem to run from $20 to $35ish.

Information gathered from: https://aws.amazon.com/route53/pricing/

**Comment by Osspial** [comment]
Doing some quick WHOIS lookups, it doesn't look like there are a whole lot of options for registering `.rs` domains. These are the two options I've found:

https://www2.ninet.rs/en/rs-domain (used by https://rustup.rs)
https://www.istanco.rs/ (used by https://rocket.rs, https://amethyst.rs)

**Comment by icefoxen** [comment]
Yeah I meant options using AWS. Sorry for being unclear.

**Comment by doppioslash** [comment]
arewegameyet.rs is on ninet at the moment
