### ISSUE TITLE
Meeting: Nov 13, 2019

### ISSUE THREAD

**Issue by Lokathor** [rust-gamedev/wg#67]
**Action Items From Last Week:**
* [ ] @kabergstrom: help gather more info about allocator use cases
* [x] @kvark: ask `granka` about custom allocators progress (also generics?)
* [ ] Debug performance (mostly generics)
* [ ] AreWeGameYet status

**Post more topics to discuss!**

**Comment by icefoxen** [comment]
We might want to talk to the embedded WG about allocator use cases too.

**Comment by kvark** [comment]
My task is done in https://github.com/rust-gamedev/wg/issues/60#issuecomment-548813540

**Comment by JeanMertz** [comment]
> AreWeGameYet status

I guess this was mostly resolved in https://github.com/rust-gamedev/wg/issues/64#issuecomment-549023291? The only open question is w.r.t. the domain itself (https://github.com/rust-gamedev/wg/issues/64#issuecomment-549025351).

**Comment by termhn** [comment]
I won't be able to make the meeting because I'll be in the middle of class, but if anyone has questions etc about `ultraviolet`, please feel free to ping me on discord/github/etc.

**Comment by Wodann** [comment]
Will anyone else be joining tonight's meeting? Remember, DST moved the meeting ahead one hour.

**Comment by Lokathor** [comment]
I forgot about the time change and told people itd be an hour from now

**Comment by Wodann** [comment]
Participants:
- Jay (Github handle?)
- @msiglreith
- @kabergstrom
- @wodann

- @kabergstrom spoke with Embark members at RustFest:
    * Most desired allocator use case: scratch buffer / linear bump allocator that is resetable (e.g. frame allocator or double frame allocator)
    * Reducing Rust compile time / performance decrease by avoiding crates that heavily rely on generics (seem happy with that solution for now)
    * Embark's cargo-deny allows you to maintain a list of banned crates and licenses
    * Thread local storage doesn't work across shared library (e.g rayon)
    * It would be good to have a standardised API for sharing thread pools (rayon, tokio, etc. all have their own thread pool)
    * It could be that crates exist that fill their needs, but end up being banned due to aforementioned limitations. In that case they might just make their own implementation that does not have these issues.

- To avoid fragmentation, it would be good for the WG to focus on standardizing more common concepts like RawHandle (e.g. ThreadPool, etc.)

- AreWeGameYet has been transferred to the WG by @ozkriff, but we still need to obtain domains

- @msiglreith opened an issue about input handling (https://github.com/rust-gamedev/wg/issues/69) as Rust support is lacking
    * Some bindings for existing C libraries are available (e.g [openxr](https://crates.io/crates/openxr))
    * @msiglreith is looking into creating a native Rust input mapping crate, but unsure where the ecosystem is going. What's winit going to do?
    * Call for review on his ecosystem overview to hear other people's opinions

- audio and input are neglected topics within gamedev
    * Nannou got a MOSS grant (partially) to work on cpal (https://nannou.cc/posts/moss_grant_announce)

- @kabergstrom released the [serde-diff](https://github.com/amethyst/serde-diff) crate. Possible use cases are Unity-style prefabs, undo-redo history systems.

**Comment by kabergstrom** [comment]
Requested to be posted here by Lokathor: https://github.com/microsoft/mimalloc

**Comment by termhn** [comment]
Also, for a bump allocator today, though must reimplement collections https://docs.rs/bumpalo

**Comment by Lokathor** [comment]
Reminder from the meeting: link times can be improved with the llvm linker in many cases. instructions here: https://github.com/rust-gamedev/wg/issues/50

**Comment by Osspial** [comment]
I brought this up in the meeting: if you're on Windows, this is by far the best step-through debugging experience I've managed to find: https://www.microsoft.com/en-us/p/windbg-preview/9pgjgd53tn86?activetab=pivot:overviewtab

**Comment by kabergstrom** [comment]
Here's the recording of the first meeting: https://www.youtube.com/watch?v=V8gpUXguLuY

**Comment by Wodann** [comment]
@Lokathor did you have recordings of the second meeting?

**Comment by Lokathor** [comment]
Karl did.. uh, and that's @kabergstrom on github I guess.

Sometimes I wish out Google Hangouts names matched our GitHub names.
