### ISSUE TITLE
Membership Listing

### ISSUE THREAD

**Issue by Lokathor** [rust-gamedev/wg#73]
It was brought to my attention that the WGs have a membership list thing. Since we're a WG we have one too.

https://github.com/rust-lang/team/blob/master/teams/wg-gamedev.toml

If you're a regular of the WG (not just meetings, but issues and other helpful work) and you're _not_ on the membership list you can comment here and we'll get you on the list.

Please note that being on the list isn't a requirement to contribute to the WG, but there are event invites (eg: the "Rust All-Hands") and other emails that sometimes go around to just people on teams and working groups.

**Comment by ozkriff** [comment]
Yeah, I'm surprised that you and @Wodann aren't listed as members.

**Comment by Lokathor** [comment]
Once in 6th grade my teacher told me "You really don't know how to promote yourself at all."

**Comment by Lokathor** [comment]
Also, I don't know what the strict limit is but [wg-embedded](https://github.com/rust-lang/team/blob/master/teams/wg-embedded.toml) seems to have 29 member slots so far so I don't think it's a super hard cap.

**Comment by AlexEne** [comment]
I raised that PR when the wg was just started, then merging it got delayed for months. Feel free to open a PR with the rest of the crew

**Comment by Wodann** [comment]
I'm planning to send a PR to add new members to our wg listing on the Rust repo by the end of this week. For now I am planning to add @Lokathor and myself. If anyone else wants to be listed, please post your:

```
name
github
github-id
email
```

**Comment by Lokathor** [comment]
(Good thing Wodann is doing the PR because I don't know my github-id)

**Comment by Wodann** [comment]
https://caius.github.io/github_id/

**Comment by aclysma** [comment]
I'd like to be included

```
Philip Degarmo
aclysma
316070
aclysma@gmail.com
```

**Comment by Wodann** [comment]
Created a [PR](https://github.com/rust-lang/team/pull/199).

**Comment by Wodann** [comment]
[PR](https://github.com/rust-lang/team/pull/199) was merged. This issue can be closed @Lokathor
