### ISSUE TITLE
Meeting: Jan 22

### ISSUE THREAD

**Issue by Lokathor** [rust-gamedev/wg#80]
From last meeting:

* [ ] Helping the alloc-wg move forward with getting their experiments in front of more people (@Lokathor)
* [ ] Discussing an update to the gamedev-wg charter so that it is more like the embedded-wg's charter (@Lokathor)

Ongoing subjects of note:
* [ ] gamedev survey?

Post more agenda items here if you have them!

**Comment by Osspial** [comment]
I'd like to further the discussion on having the gamedev working group own texture management/asset format crates.

**Comment by Lokathor** [comment]
Update on the charter issue:

I PM'd @nikomatsakis on Zulip and they agreed that any charter changes should generally be signed off on by both the rust org and the wg itself, but also they said that this is new territory that hasn't come up before.

Obviously the rust org can't sign off on any new things until we have a concrete proposal, so we need to develop that as a WG first.

I'm therefore suggesting the following tentative order of events based on the usual PR/RFC workflow we're all used to as Rust devs:
* We, the working group, develop the new charter as a PR to this repo.
* We will wait a minimum of 1 meeting so that we can discuss the PR at a Hangouts meeting, for people who do better in a spoken word format. Also just to avoid rushing too quickly on anything.
* Once the working groups has agreed that we want to accept the new charter, we link it to the rust org (core team?) for them to also endorse it (they may request changes, iterate on wording, etc, usual PR stuff)
* Once both organizations agree to the new charger we merge that PR.

I'm going to propose that @kabergstrom lead the actual PR itself (if you don't mind). You since you seemed to have the clearest idea of exactly what you were looking for in a revised charter.

**Comment by nikomatsakis** [comment]
Hi all,

I'm curious whether charter changes are truly required? Skimming over the original charter, I see this (emphasis mine):

> * We will not build games or a game engine as this working group. However, **we can create low-level tooling or libraries** that are aimed at the healthy growth of the ecosystem and is not meant to be opinionated or favor an engine over another.
> * We will not be curators for "approved" game development libraries. Our purpose is to help such engines to exist, not to promote one library over another.

I guess the question then becomes, what sort of libraries did you have in mind?

**Comment by nikomatsakis** [comment]
I think the main question to consider is to what extent the library *competes* with pre-existing libraries. If there is overlap, then I think the *ideal* is that the authors of those other libraries are also contributing and involved in the design, but regardless one should be careful in how the library is presented.

Another option to consider, I think, is to create the library in a separate org (or someone's github) but just come to the working group to help get feedback about specific aspects of its design. 

The danger is that there is the appearance (or reality) that the working group is being used to give one project an edge over another. The truth is that I think there isn't that much danger about this: people will tend to use the projects that are best technically, and I don't think that a "stamp of officialness" from the Rust org (or a WG thereof) is all that important. 

But by the same token, I see no reason not to set things up as "an independent project that is developed by people active in the WG" vs "a project developed by the WG itself".

Of course, if the library is more of an "interop standard", or filling a gap where nothing exists, then perhaps these concerns don't apply.

(I do think it makes sense, btw, for the WG to maintain a kind of "canonical listing" of libraries, as well.)

**Comment by AlexEne** [comment]
The spirit of that sentence (probably not so clearly worded) is to create things that are useful to more than just a single engine and to also avoid proposals about an engine creation. It's not about competition or overlap.

That's why it mentions low-level /foundational libraries that might be used by more than one engine e.g. spirv-rust was something we said previously it's ok to happen here and so on. Math libs were another mention but I don't think there is any sort of consensus on what is missing there.

Is there a particular library that should be here or started here that you have in mind?

**Comment by AlexEne** [comment]
To the charter changes that you're proposing @Lokathor, I insist on following with the current charter that states that: No decisions are made on discord or Wg-meetings. 
Let's open an issue with the proposal where that's discussed (as the current setup was agreed).

**Comment by nikomatsakis** [comment]
@AlexEne 

> Is there a particular library that should be here or started here that you have in mind?

I'm not sure if that was addressed to *me* -- if so, certainly not. =) @Lokathor had mentioned to me a desire to possibly alter the charter so as to enable the group to author libraries, and I  was just pointing out that the charter seems to already allow that, at least in some cases, and giving some general thoughts on WGs developing libraries. 

I do think that concern over being engine-specific is one thing. I think there can be other kinds of concerns that arise too. But overall I would prefer if we take a "the more the merrier" approach when it comes to libraries! I favor experimentation and development, especially in areas like this. I'm basically just interested in finding a "best practices" to enable us to develop more libraries happily and productively.

**Comment by AlexEne** [comment]
Yeah, I pinged the wrong person :D,  let's have this charter discussion on a separate issue as I mentioned above with what changes are proposed.

**Comment by Lokathor** [comment]
Hey hey slow down folks. People seem to be thinking on some sort of accelerated time table that I never said.

I put an agenda item to _discuss_ desired changes to the charter.

That is all I said. There is no specific proposal. I just said "let's have this discussion".

* This is in response to the fact that, at that last meeting, everyone who showed up felt very hamstrung by the current common reading of the charter, and unable to usefully participate in the working group. Basically like we're just wasting our time.
* Personally, I think that a volunteer group where people feel like they're wasting their time isn't going to last long, and I would like the WG to last instead of dying out.
* So, to be clear, I do _not_ myself have a library idea in mind or anything like that. But I do know how to see bad morale when it's fermenting, and I don't want it to just sit there unaddressed.
* @AlexEne: I don't follow your reasoning about a PR being a bad format once people have talked some about the sort of things they'd want to see in a change. A PR _is_ an issue thread. Anything you can do in an issue thread you can also do in a PR.

**Comment by AlexEne** [comment]
A PR is not an ideal place to have the discussion because it can spawn multiple threads in the form of comments about various sentences.

An issue thread is more linear and has no danger of multilple discussions happening at the same time, l and that is why I suggested it. Also for the purpose of recording a decision and the process it got to where it is, a linear format is better.

**Comment by Lokathor** [comment]
Alright that makes sense.

**Comment by AlexEne** [comment]
Besides that, it is clear that at least the library point in the charter wording needs some extra explanation at least and better wording at least as it seems to have been interpreted in a different way than it was intended to by Niko and quite likely others.

The purpose of that was clear in the heads of ppl reviewing and writing that sentence(see explanation from me above) but that clarity and purpose didn't come through so we def should adjust it.

Other charter changes are fine too and as I said above I, highly like the other leads and members are open to any proposals.

**Comment by aclysma** [comment]
#82: Rust All-Hands 2020 would be good to touch on.
 * Anything we want to see added to the list?
 * Is there anything we should do/discuss now in preparation for that? (For example, writing up more details on the problem and potential solutions, or a specific solution if we have one in mind.)
 * Are there any groups we'd like to help represent? (industry professionals, hobbyists, etc.) If so, is there anything we should be doing now to collect opinions/ideas? (For example, @ some folks on twitter to ask for their feedback.)

I'm still not sure if we have anyone that's committed to going, but even if we don't these discussions could still be useful and we could still pass along anything we like by text.

**Comment by TimDiekmann** [comment]
> Helping the alloc-wg move forward with getting their experiments in front of more people

I can try to arrange to attend the meeting on Wednesday, but I cannot yet agree to do so due to private time constraints. In any way please feel always free to ping me on Zulip/Discord, file issues, or make PRs!
I am excited that my crate is being discussed in this AG. On the one hand this is the first concrete user of `alloc-wg` (that I'm aware of), on the other hand I was always enthusiastic about gamedev :slightly_smiling_face:

**Comment by Lokathor** [comment]
Video up: https://youtu.be/r4aHR7i8d1Q
Next Meeting: https://github.com/rust-gamedev/wg/issues/83

**Comment by TimDiekmann** [comment]
> Video up: https://youtu.be/r4aHR7i8d1Q

Regarding wg-allocators: Can't add much more here. By now I'm working on pushing the first changes to the trait upstream.
