### ISSUE TITLE
Moving ecs_bench to GDWG

### ISSUE THREAD

**Issue by erlend-sh** [rust-gamedev/wg#89]
I talked to @lschmierer of [ecs_bench](https://github.com/lschmierer/ecs_bench) and he’d be happy to move the repo to our org for community maintenance.

> I think there are some open feature request about other/new ecs libraries. As I currently don't have the capacity to work on the project, I think it would benefit from moving it to the workgroup.
> 
> Some notes on the workflow: As far as I remember, I pushed all changes and updates to the bench branch. The benchmark was then run automatically by Travis and the results were pushed back by Travis to the master branch. I think that needs to be documented somewhere.
Might also make sense to migrate to the new GitHub Actions, but haven't really looked into it.

This seems like the kind of low-maintenance library that this WG is well suited for. Benchmarks benefit from neutrality, and the individual library authors have an incentive to help maintain this crate so the burden isn’t really on the wg to keep it up to date.

**Comment by Ralith** [comment]
Worth noting that running benchmarks on shared machines (i.e. any free CI provider) is a bit dubious, especially if granted the appearance of being an official judgement.

**Comment by erlend-sh** [comment]
@tomgillen has created a new, more advanced ECS benchmark suite: https://github.com/TomGillen/ecs_bench_suite

He is "not adverse to moving it".

**Comment by erlend-sh** [comment]
This is now done! Further coordination measures will be discussed here: https://github.com/rust-gamedev/ecs_bench_suite/issues/3
