### ISSUE TITLE
Meeting summary 2019-06-12

### ISSUE THREAD

**Issue by erlend-sh** [rust-gamedev/wg#9]
- We discussed https://github.com/rust-gamedev/wg/pull/5/ and agreed we wanna get it merged sooner rather than later. It's a living document that will get tweaked continuously over time so the most important thing right now is to have a starting point published.

- We talked about what it means to be library/engine agnostic. In order to provide basic teaching material for gamedev essentials extending to the likes of audio, input, graphics rendering etc. the WG will indirectly support certain libraries when using them for demonstration & teaching purposes. We are fine with this level of bias as it's easily kept in check by making sure to mention relevant alternatives.

- We talked about https://github.com/rust-gamedev/wg/issues/3 and concluded we'll be fine with GitHub as our single "source of truth" right now, including longform discussion. We can use GitHub issues for all asynchronous discussions until it starts really hurting.

**Comment by AlexEne** [comment]
Is it ok if I close this? In the future I think a condensed status could be sent out as a post in the rust-gamedev.github.io site?
