### ISSUE TITLE
Should the wg volunteer to maintain winapi?

### ISSUE THREAD

**Issue by AlexEne** [rust-gamedev/wg#91]
https://github.com/retep998/winapi-rs/issues/867

## Why?
This fits into the foundational crates category mentioned in the wg charter.
Game developers are mainly using windows

## Why not?
Extra work for us to merge things in it from time to time and maybe set up some extra tests, etc.?

The why in my opinion outweighs the why not so therefore I made this proposal here.

**Comment by Lokathor** [comment]
Well obviously we should ping @retep998 to see if they're even _interested_ in the idea.

**Comment by retep998** [comment]
I have been pinged.

**Comment by Lokathor** [comment]
> ... to see if they're even _interested_ in the idea.

**Comment by minecrawler** [comment]
@Lokathor 
if I understood the linked issue in the OP correctly, @retep998 does not have the time and motivation to continue development on winapi-rs at the moment:

> I do lack the time and willpower to maintain winapi by myself

and is open to others offering help maintaining the project:

> Are you offering to help [..] ?

From there, the following questions do have to be answered:

- does the WG want to maintain the crate?
- how would that look like? Would @retep998 have to transfer the project and all rights to the WG?
- would @retep998 agree to such terms?

**Comment by Lokathor** [comment]
Well with that bullet point list:
* Speaking for just myself: We should help winapi where we can.
* I don't think the repo needs to move, though it could.  The main thing to be gained by a move would be to help signal to the ecosystem that the crate is moving to be more community managed instead of being basically all work put on retep998 all the time.
* Bullet three is the one I pinged retep998 for in the first place.

**Comment by AlexEne** [comment]
I think it should move somewhere where at least more ppl have merge rights, as there are a bunch of open PRs that are important for example [this](https://github.com/retep998/winapi-rs/pull/812).

I don't mind being part of this wg and merging them and adding some extra tests, etc.

**Comment by retep998** [comment]
If the winapi repo is going to be moved to a working group, it should be moved to the windows wg: https://github.com/rust-windows/wg

**Comment by AlexEne** [comment]
Didn't know about the windows wg. Makes sense
