### ISSUE TITLE
raw-window-handle maintenance

### ISSUE THREAD

**Issue by msiglreith** [rust-gamedev/wg#94]
I would like to raise some awareness for the current situation of `raw-window-handle` which is currently mostly unmaintained.
As the crate originated from this wg I created the topic here. Issues right now are related to:

- Creating new releases
- Extending support for new platforms
- Disucss API changes based on user experience

As dealing with all different platforms is difficult, therefore, having multiple people involved would be great.

**Comment by Lokathor** [comment]
Could you expand more on what new platforms you'd like to see?

And what API changes?

**Comment by msiglreith** [comment]
@Lokathor I'm mostly referring to the open issues and PR:

- platforms: currently UWP & redox seem to be requested at least
- API changes: `non_exhaustive`, https://github.com/rust-windowing/raw-window-handle/issues/56 and https://github.com/rust-windowing/raw-window-handle/issues/54

**Comment by Lokathor** [comment]
Well of course @Osspial has to be on board for any changes.

Getting new platforms is mostly a matter of PRs from people who know how to work that platform. I'm sure once things are waiting on review Osspial will have a lot more incentive to actually review it. It's harder to get up the energy to do something new yourself, particularly during 2020.

**Comment by Lokathor** [comment]
Hello, I am now maintainer on the `raw-window-handle` crate.

Accordingly, I'm going to close this issue here. Please feel free to file any new issues in the tracker there.
