### ISSUE TITLE
New WG members

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/wg#96]
I propose that @logicsoup, @patchfx, and @AngelOnFira be added to the list of WG's members.

- @logicsoup:
  > Hey folks. I would like to become a member of the WG (i.e contribute to meetings, issues, key decisions) as I would like to help out more. I will start by adding the [Garden](http://cyberplant.xyz) info to the newsletter myself, and I’m working right now (very slowly) on a couple of graphics things that I’ll open source later. But I’ve been thinking lately how I don’t want to take the Rust community for granted, so I would like to try to become an active member of the WG, if you’ll have me.

  (_from [WG's DIscord channel](https://discord.com/channels/442252698964721669/587379891758956544/767461265295409193)_)

- @patchfx is the host of the new awesome [Rust GameDev Podcast](https://rustgamedev.com).

- @AngelOnFira is one of the main Veloren developers.

_Related to #73 ("Membership Listing")_

**Comment by erlend-sh** [comment]
Furthermore, I’d like to nominate @ozkriff as Team Leader ;) We don’t yet attach much meaning to this title besides [listing it here](https://www.rust-lang.org/governance/wgs/gamedev) and granting Owner privileges in this org.

Whatever it means, as the most active WG member around you’re certainly entitled to it!

**Comment by ozkriff** [comment]
Considering that WG team lead's responsibilities are undefined, wanted to note that I'm mostly concentrated on our [Twitter](https://twitter.com/rust_gamedev) and [newsletter](https://github.com/rust-gamedev/rust-gamedev.github.io/) (and [AWGY](https://github.com/rust-gamedev/arewegameyet) to a lesser extent). I'm struggling to find enough time even for them, so it's unlikely that I'll participate in other WG's tasks.

**Comment by kvark** [comment]
I haven't had any interactions with the people in the main subject. However, I can definitely vouch for @ozkriff :) 🎖️

**Comment by ozkriff** [comment]
Ok, so I'll send a PR to rust-lang/team today.

**Comment by AlexEne** [comment]
Fine by me. @ozkriff  Do you have the required status on github?

**Comment by ozkriff** [comment]
PR: https://github.com/rust-lang/team/pull/479

@AlexEne yep, I've received a notification that I was added to the org's owners this morning.

**Comment by ozkriff** [comment]
:tada: Aaaand it's done: https://www.rust-lang.org/governance/wgs/gamedev
